#!/bin/bash
# Deconz to mqtt
#
# description: Deconz to mqtt

case $1 in
    start)
        /bin/bash /usr/local/bin/deconzmqtt-start.sh
    ;;
    stop)
        /bin/bash /usr/local/bin/deconzmqtt-stop.sh
    ;;
    restart)
        /bin/bash /usr/local/bin/deconzmqtt-stop.sh
        /bin/bash /usr/local/bin/deconzmqtt-start.sh
    ;;
esac
exit 0